// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useEffect, useState } from 'react';
import Home from './layouts/Home';
import axios from 'axios';
import { baseURL, authenticationCheckURL } from './constants/Constants';
import { BrowserRouter, Navigate, Route, Router, Routes } from 'react-router-dom';
import Login from './layouts/Login';
import Signup from './layouts/Signup';
const App = () => {
	const [isAuthenticated, setIsAuthenticated] = useState(null);

	useEffect(() => {
		axios.get(
			baseURL + '/api/auth/check',
			{
				withCredentials: true
			}
		)
			.then(res => {
				console.log('auth check res:', res);
				console.log('authenticated:', res.data.authenticated);
				setIsAuthenticated(res.data.authenticated);
			})
			.catch(err => {
				console.log('err in auth check:', err);
			})
	}, [])

	// return (
	// 	<BrowserRouter>
	// 		<Routes>
	// 			<Route
	// 				path="/*"
	// 				element={isAuthenticated ? <Home /> : <Navigate to="/login" replace />}
	// 			/>
	// 			<Route path="/login" element={<Login isAuthenticated={setIsAuthenticated} />} />
	// 			<Route
	// 				path="/home"
	// 				element={isAuthenticated ? <Home /> : <Navigate to="/login" replace />}
	// 			/>
	// 		</Routes>
	// 	</BrowserRouter>
	// );

	return (
		<BrowserRouter>
			{/* Wait for auth check before rendering routes */}
			{isAuthenticated === null ? (
				<div>Loading authentication...</div>
			) : (
				<Routes>
					<Route
						path="/home"
						element={isAuthenticated ? <Home /> : <Navigate to="/login" replace />}
					/>
					<Route
						path="/login"
						element={<Login isAuthenticated={setIsAuthenticated} />}
					/>
					<Route
						path="/signup"
						element={<Signup isAuthenticated={setIsAuthenticated} />}
					/>
					{/* Optional: catch-all, redirect */}
					<Route
						path="*"
						element={<Navigate to={isAuthenticated ? "/home" : "/login"} replace />}
					/>
				</Routes>
			)}
		</BrowserRouter>
	);
}

export default App;
