// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useState, useEffect } from "react";
import "../style/AddTodoModal.css"; // Optionally add modal CSS here

const categories = [
	{ name: "None", color: "#9e9e9e" },
	{ name: "Home", color: "#fc859e" },
	{ name: "School", color: "#ffd26a" },
	{ name: "Shopping list", color: "#65bcff" },
];

const statusList = [
	{ name: "Not Started"},
	{ name: "In Progress"},
	{ name: "Completed"}
];

const AddTodoModal = ({
	show,
	onClose,
	onSave,
	loading = false, // Optional: show loader while saving
	todo
}) => {
	const [title, setTitle] = useState("");
	const [description, setDescription] = useState("");
	const [category, setCategory] = useState("");
	const [dueDate, setDueDate] = useState("");
	const [id, setId] = useState("");
	const [status, setStatus] = useState("");
	// Reset form when modal opened/closed
	useEffect(() => {
		if (show) {
			if(todo != null) {
				setTitle(todo.title);
				setDescription(todo.description == null ? "" : todo.description);
				setCategory(todo.category == null ? "" : todo.category);
				setDueDate(todo.dueDate);
				setId(todo.id);
				setStatus(todo.status)
			} else {
				setTitle("");
				setDescription("");
				setCategory("");
				setDueDate("");
				setId("");
				setStatus("");
			}
		}
	}, [show]);

	const handleSave = () => {
		// if (!title.trim()) return; // Optionally validate more fields
		onSave({ id, title, description, category, dueDate, status });
		onClose(true);
	};

	if (!show) return null;

	return (
		<div className="modalOverlay">
			<div className="modalContent">
				<h2>Add New Task</h2>
				<div className="formField">
					<label>Title</label>
					<input
						type="text"
						value={title}
						onChange={e => setTitle(e.target.value)}
					/>
				</div>
				<div className="formField">
					<label>Description</label>
					<textarea
						value={description}
						onChange={e => setDescription(e.target.value)}
					/>
				</div>
				<div className="formField">
					<label>Category</label>
					<select
						value={category}
						onChange={e => setCategory(e.target.value)}
					>
						{categories.map(cat => (
							<option key={cat.name} value={cat.name}>{cat.name}</option>
						))}
					</select>
				</div>
				<div className="formField">
					<label>Due Date</label>
					<input
						type="date"
						value={dueDate}
						onChange={e => setDueDate(e.target.value)}
					/>
				</div>
				<div className="formField">
					<label>Status</label>
					<select
						value={status ? status : ""}
						onChange={e => setStatus(e.target.value)}
					>
						{statusList.map(stat => (
							<option key={stat.name} value={stat.name}>{stat.name}</option>
						))}
					</select>
				</div>
				<div className="modalActions">
					<button onClick={handleSave} className="saveBtn">
						{loading ? "Saving..." : "Save"}
					</button>
					<button onClick={onClose} className="cancelBtn">Cancel</button>
				</div>
			</div>
		</div>
	);
};

export default AddTodoModal;
