// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useEffect, useState } from 'react';
import '../style/App.css';
// import NavBarCmp from './NavBarCmp';
import { baseURL, getTodosURL, addTodoURL, updateTodoURL, logoutURL, deleteURL } from '../constants/Constants';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';
import AddTodoModal from './AddTodo';
// Category config
const categories = [
    { name: 'All', color: '#cccccc' },
    { name: 'None', color: '#9e9e9e' },
    { name: 'Home', color: '#fc859e' },
    { name: 'School', color: '#ffd26a' },
    { name: 'Shopping list', color: '#65bcff' }
];

const initialTodos = [
    // { id: 1, title: 'Example task', category: 'Home' },
    // { id: 2, title: 'Example task 2', category: 'Home' },
    // { id: 3, title: 'Math homework', category: 'School' },
    // { id: 4, title: 'Buy tomatoes', category: 'Shopping list' },
];

const Home = () => {
    const navigate = useNavigate();
    useEffect(() => {
        axios.get(baseURL+'/api/auth/check',
            {
                withCredentials: true
            }
        )
        .then(res => {
            console.log('res:',res);
            if(res.data.authenticated) {
                // setIsAuthenticated(res.data.authenticated);
                console.log('authenticated');
                getTodos(); //comment this line to show the default todos
            } else {
                navigate('/login', {replace: true});
                console.log('not authenticated');
            }
        })
        .catch(error => {
            console.log(error.message);
        })
    }, []);

    const getTodos = () => {
        axios.get(
            getTodosURL,
            {
                withCredentials : true
            }
        )
        .then(res => {
            console.log('get todos res:',res);
            setTodos(res.data);
        })
    }

    const [todos, setTodos] = useState(initialTodos);
    const [selectedCategory, setSelectedCategory] = useState('All');
    const [newTask, setNewTask] = useState('');
    const [statusFilter, setStatusFilter] = useState('All');
    const [showModal, setShowModal] = useState(false);
    const [modalLoading, setModalLoading] = useState(false);
    const [todoToEdit, setTodoToEdit] = useState({});
    const categoryColor = (cat) => categories.find(c => c.name === cat)?.color;

    // const filteredTodos = selectedCategory === 'All'
    //     ? todos.filter(todo => (todo.status === statusFilter || (statusFilter === 'All' && todo)))
    //     : todos.filter(todo => todo.category === selectedCategory).filter(todo => (todo.status === statusFilter || (statusFilter === 'All' && todo)));

    // const filteredTodos = todos.filter(todo => {
    //     // Category check: "All" means pass everything, otherwise match
    //     const matchesCategory =
    //         selectedCategory === 'All' || todo.category === selectedCategory;

    //     // Status check: "All" means pass everything, otherwise match
    //     const matchesStatus =
    //         statusFilter === 'All' || todo.status === statusFilter;

    //     return matchesCategory && matchesStatus;
    // });

    const filteredTodos = todos.filter(todo => {
        // If "All" is selected in categories, allow all, else match the selectedCategory.
        const matchesCategory = selectedCategory === 'All' || todo.category === selectedCategory;

        // If "All" is selected in status, allow all, else match the statusFilter.
        const matchesStatus = statusFilter === 'All' || todo.status === statusFilter;

        // Only include todos matching BOTH selected filters.
        return matchesCategory && matchesStatus;
    });

    const addTodo = () => {
        setTodoToEdit(null);
        setShowModal(true);
    };

    const handleEditTodo = (todo) => {
        console.log('todo from edit:', todo);
        setTodoToEdit(todo);
        setShowModal(true);
    }

    const applyStatusFilter = (status) => {
        setStatusFilter(status);
        console.log('status:',status)
    }

    const handleSaveModal = (todo) => {
        console.log('handle save called', todo);
        if(!todo.id) {
            axios.post(
                addTodoURL,
                todo,
                {
                    withCredentials: true
                }
            )
            .then(res => {
                console.log('todo save res:', res);
                if(res.status == 201) {

                    // filteredTodos.push(res.data);
                    // let todo = todos.push(res.data);
                    // setTodos(todo);
                    // setShowModal(false);
                    // setTodoToEdit(null);
                    window.location.reload();
                }
            })
            .catch(err => {
                console.log('err in saving todo:', err);
            })
        } else {
            axios.put(
                updateTodoURL,
                todo,
                {
                    withCredentials: true
                }
            )
            .then(res => {
                console.log('todo save res:', res);
                if(res.status == 200) {
                    // filteredTodos.push(res.data);
                    setTodos(prev => prev.map(td => td.id === todo.id ? res.data : td));
                    setShowModal(false);
                    setTodoToEdit(null);
                }
            })
            .catch(err => {
                console.log('err in saving todo:', err.response);
            })
        }
    }

    const handleLogout = () => {
        axios.post(
            logoutURL,
            {},
            {withCredentials:true}
        )
        .then(res => {
            console.log('logout res:',res);
            navigate('/login', {replace: true});
        })
        .catch(err => {
            console.log('logout error', err);
            navigate('/login', {replace: true});
        })
    }

    const handleDeleteTodo = (todo) => {
        console.log('```delete todo called:', todo);
        axios.delete(
            deleteURL+'/'+todo.id,
            {withCredentials:true}
        )
        .then(res => {
            if(res.status == 200) {
                console.log('delete success:', res);
                window.location.reload();
            }
        })
        .catch(err => {
            console.log('err in delete:', err.response);
        })
    }

    return (
        <>
            <div className="container">
                {/* Sidebar */}
                <aside className="sidebar">
                    <div className="sidebarSection">
                        <div className="sidebarTitle">Tasks</div>
                    </div>
                    <div className="sidebarSection">
                        <div className="sidebarSubtitle">Categories</div>
                        <ul className="categoryList">
                            {categories.map(cat => (
                                <li
                                    key={cat.name}
                                    className={`categoryItem ${selectedCategory === cat.name ? 'active' : ''}`}
                                    onClick={() => setSelectedCategory(cat.name)}
                                >
                                    <span className="categoryDot" style={{ background: cat.color }} />
                                    {cat.name}
                                </li>
                            ))}
                        </ul>
                    </div>
                    <div className="sidebarSection">
                        {/* <div className="sidebarTitle" onClick={() => {handleLogout()}}>Logout</div> */}
                        <button
                            className="sidebarLogoutBtn"
                            onClick={handleLogout}
                            aria-label="Logout from your account"
                            // ...styles as above
                        >
                            Logout
                        </button>
                    </div>
                    <div className="sidebarSection">
                        <div className="sidebarTitle">Settings</div>
                    </div>
                </aside>

                {/* Main Content */}
                <main className="mainContent">
                    <header className="mainHeader">
                        <h2>Tasks</h2>
                        <div className="filters">
                            <button className="filterBtn active" onClick={() => applyStatusFilter('All')}>All</button>
                            <button className="filterBtn" onClick={() => applyStatusFilter('In Progress')}>In Progress</button>
                            <button className="filterBtn" onClick={() => applyStatusFilter('Not Started')}>Not Started</button>
                             <button className="filterBtn" onClick={() => applyStatusFilter('Completed')}>Completed</button>
                        </div>
                    </header>
                    <ul className="todoList">
                        {filteredTodos.map(todo => (
                            <li key={todo.id} className="todoItem">
                                <span className="todoCircle" />
                                <div>
                                    <div className="todoText">{todo.title}</div>
                                    <div className="todoCategory">
                                        <span className="categoryDot" style={{ background: categoryColor(todo.category) }} />
                                        {todo.category}
                                    </div>
                                </div>
                                <div className="todoActions">
                                    <span className="todoIcon" onClick={() => {handleEditTodo(todo)}}>✏️</span>
                                    <span className="todoIcon" onClick={() => {handleDeleteTodo(todo)}}>🗑️</span>
                                </div>
                            </li>
                        ))}
                    </ul>
                    {/* <div className="addTaskRow">
                        <input
                            type="text"
                            className="addTaskInput"
                            placeholder="Add a task"
                            value={newTask}
                            onChange={e => setNewTask(e.target.value)}
                            onKeyDown={e => e.key === 'Enter' && addTodo()}
                        />
                        <button className="addTaskBtn" onClick={() => addTodo()}>
                            <span className="plusIcon">＋</span>
                        </button>
                    </div> */}
                    <div className="centerAddButtonRow">
                        <button className="centerAddBtn" onClick={addTodo}>
                            ＋ Add Task
                        </button>
                    </div>
                </main>
                <AddTodoModal
                    show={showModal}
                    onClose={() => setShowModal(false)}
                    onSave={handleSaveModal}
                    loading={modalLoading}
                    todo={todoToEdit}
                />
            </div>
        </>
    );
}

export default Home;
